---
title: "The Logic of Alliance Formation Among Rebel Groups"
author: "David Bowden"
date: "`r paste(format(Sys.time(), '%B'), ' ', as.numeric(format(Sys.time(), '%d')), ',', ' ', format(Sys.time(), '%Y'), sep='')`"
output:
    bookdown::pdf_document2:
        includes:
            in_header: preamble.tex
documentclass: article
bibliography: /Users/david/Dropbox/library.bib
fontsize: 12pt
fontfamily: tgpagella
geometry: margin=1in
numbersections: true
toc: no
abstract:
    "Multi-party civil wars are among the most severe conflicts, yet we know relatively little about the determinants of rebel movement structure. I focus on a key aspect of this process - the conditions under which rebel groups are likely to form alliances. I argue that rebel groups will prefer alliances with groups that have similar non-sectarian ideologies, and dissimilar sources of material support. Groups with dissimilar ideologies or rival claims for support bases such as natural resources or an ethnic constituency should be unlikely to collaborate. I test this theory using data on alliances between 29 militant organizations in the Syrian civil war. Using an TERGM model of network formation, I show that ideological similarity indeed is a strong predictor of alliance formation. However, I find that groups competing for similar territories, natural resources, or the representation of the same religious minority are not any less likely than others to form alliances. These results call into question existing theories that expect alliances to be formed primarily on the basis of relative power."
---

 ```{r setup, include=F}
 knitr::opts_chunk$set(echo=F, error=F, message=F, warning=F, cache=T, results='asis')
```

\doublespacing

```{r child='formation_intro.txt'}
```

```{r child='formation_lit.txt'}
```

```{r child='formation_framework.txt'}
```

```{r child='formation_theory.txt'}
```

```{r child='formation_design.Rmd'}
```

```{r child='formation_results.Rmd'}
```

```{r child='formation_conclusion.txt'}
```

# References

\indent

\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}

\singlespacing
